### ISSUE TITLE
When there is a prefix argument, switch to a shell acordingly, not close it

### ISSUE THREAD

**Issue by tuhdo** [kyagi/shell-pop-el#23]
Currently, when we are already in a shellpop window, execute `shell-pop` always closes the shellpop window. But it's convenient to switch between shells with prefix argument. We should have a check that if users supply a prefix argument, it should switch shell intead.

**Comment by syohex** [comment]
How about #24 ?

![shell-pop-23](https://cloud.githubusercontent.com/assets/554281/7875301/27bb07ba-05f6-11e5-954d-a815d55bac3e.gif)
