### ISSUE TITLE
shell-pop cannot close its shell window when the window is maximized

### ISSUE THREAD

**Issue by tuhdo** [kyagi/shell-pop-el#25]
How to reproduce:

- pop a window.
- maximize it.
- Now, try to use `shell-pop` command again. The window won't be able to close and an error is thrown.

**Comment by syohex** [comment]
I cannot reproduce this issue with Emacs 24.3 and Emacs Head.

Would you tell us in more detail ?
- Emacs version
- minimum configuration for reproducing this issue
- error message
etc

**Comment by tuhdo** [comment]
My Emacs is 24.5. I reproduced it with `emacs -q` and installed a fresh `shell-pop`. Probably the steps were not worded correctly. Here is the recipe, again (assumed `shell-pop` already installed):

- `M-x shell-pop`.
- `C-x 1` the shell window.
- `M-x shell-pop` again.
- Error: `Attempt to delete minibuffer or sole ordinary window`

**Comment by syohex** [comment]
I have merged #26. Please check latest version.

**Comment by tuhdo** [comment]
Thank you very much! Works nicely.
