### ISSUE TITLE
why vertical layout is not supported?

### ISSUE THREAD

**Issue by autosquid** [kyagi/shell-pop-el#30]
we NEED vertical layout with `left`, `right` options

**Comment by syohex** [comment]
@autosquid Thanks for suggestion. I implement this feature at #31. Please check it.

**Comment by autosquid** [comment]
@syohex  thanks for quick response! Great work!! Now I can stay my emacs all day long! Please push to  melpa, could wait any longer to see it there!!

**Comment by autosquid** [comment]
Oh, I did not notice that you are not the creator `shell-pop-el`.  @kyagi  seems not actively updating this work :(

**Comment by syohex** [comment]
I have merged #31. Please try latest version(Some hours are necessary until MELPA updates repository).

```lisp
(setq shell-pop-window-position "right") ;; or "left"
```
