### ISSUE TITLE
shell-pop-shell change directory with dired

### ISSUE THREAD

**Issue by darkfeline** [kyagi/shell-pop-el#38]
When `shell-pop-shell` is called in a dired buffer, the resultant pop-up shell doesn't cd correctly for paths containing the user's home directory:

    # Example opening popup shell in dired buffer /home/bob/foo
    $ cd \~/foo/
    cd: no such file or directory: ~/foo

EDIT: `shell-pop-shell` is `shell-pop` with the shell type set to "shell".

**Comment by darkfeline** [comment]
In dired, `default-directory` starts with a tilde: `~/foo` instead of `/home/bob/foo`.  I don't know why this is, it might be caused by another package.

The tilde can be expanded using `expand-file-name` at https://github.com/kyagi/shell-pop-el/blob/master/shell-pop.el#L209 although that is not the intended usage of `expand-file-name`.

**Comment by syohex** [comment]
Thanks for reporting issue.
I have fixed at this issue at #39. Please check latest version.

**Comment by darkfeline** [comment]
Thanks for the quick fix.
