### ISSUE TITLE
Set the shell type in dot-emacs.

### ISSUE THREAD

**Issue by ReneFroger** [kyagi/shell-pop-el#43]
## Setup:
GUI version GNU Emacs 25.0.50.1 (x86_64-w64-mingw32)
of 2015-07-25 on KAEL

[Compiled from EmacsW64.](http://emacsbinw64.sourceforge.net/)

Shell-pop, using the latest version of shell-pop  from MELPA

Windows 7 x64 bit.

## Situation:
How could I set up the type of shell in my Dot-emacs?

When I run <kbd>M-x eshell</kbd>, the eshell pop ups and is working fine.

When I set it up in my dot-Emacs with the following:

    (setq shell-pop-shell-type '("eshell" "*eshell*" (lambda () (eshell))))

And I call <kbd>M-x shell-pop</kbd>, I get the default shell instead Eshell. 

When I do <kbd>C-h v</kbd> `shell-pop-shell-type`, then I get the following:

    shell-pop-shell-type is a variable defined in ‘shell-pop.el’.
    Its value is ("eshell" "*eshell*" (lambda nil (eshell)))
    Original value was 
    ("shell" "*shell*"
    (lambda nil
    (shell)))

So somewhere the Eshell configuration didn't get applied. Any suggestion to debug this?

**Comment by syohex** [comment]
Could you add following code your configuration file and try again ?

```lisp
(custom-set-variables
 '(shell-pop-term-shell "eshell")
 '(shell-pop-shell-type '("eshell" "eshell" (lambda () (eshell)))))
```

**Comment by ReneFroger** [comment]
@syohex thanks for your reply, but it didn't help, I still get the default shell.

**Comment by syohex** [comment]
Hmm, I cannot reproduce with above configuration.

**Comment by ReneFroger** [comment]
You're right. It turned out that the configuration file for pop-shell was never initialized. Thanks for your help and support, Syohex, it's really appreciated!
