### ISSUE TITLE
Popping out shell window changes other buffer

### ISSUE THREAD

**Issue by bmag** [kyagi/shell-pop-el#47]
If I pop up a shell, switch the buffer in the non-shell window, and then pop out the shell, the buffer in the non-shell window is switched back to the original one. Is this the desired behavior, or is it a bug?

Reproduction recipe:
- `emacs -Q -l /path/to/shell-pop.el` - start emacs and load shell-pop.el
- `C-x b foo RET` - switch to buffer "foo"
- `M-x shell-pop` - pop up a shell
- `C-x o` - select original window
- `C-x b bar RET` - switch to buffer "bar"
- `C-x o` - select shell window. There are now two windows - one for "bar" buffer, one for shell buffer.
- `M-x shell-pop` - pop out the shell

Observed behavior: there is a single window, and it shows buffer "foo".
Expected behavior: there is a single window, and it shows buffer "bar".

**Comment by syohex** [comment]
> Is this the desired behavior, or is it a bug?

It is the desired behaviour. shell-pop-out restores original window when shell-pop was invoked.

**Comment by bmag** [comment]
I like using `M-x shell-pop` for both opening and closing the shell, but usually I prefer `shell-pop-out` to delete the shell window without restoring the other windows. Of course I can use `M-x delete-window` for closing, but I like using `M-x shell-pop` for closing as well. Would you accept a patch that adds a user-option for disabling the restoration of the other windows? It won't change the current default behavior.

**Comment by syohex** [comment]
Yes, we welcome patch.

**Comment by bmag** [comment]
Made a PR. Wasn't sure about changing the README, so I left it as it is.
