### ISSUE TITLE
Full Span and Neotree

### ISSUE THREAD

**Issue by jupl** [kyagi/shell-pop-el#50]
When I have `neotree` and `shell-pop` I do the following:
1. `M-: (setq shell-pop-full-span t)` to enable full span.
2. `M-x neotree-toggle` to toggle Neotree to be visible.
3. `M-x shell-pop` to try and open shell.

For step 3, the shell does not pop up and instead I get the error message `Cannot split side window or parent of side window`. This is counterintuitive because I can only have one or the other but not both.

**Comment by syohex** [comment]
Because neotree window does not allow `split-window`.

**Comment by cornfeedhobo** [comment]
@kyagi I think this issue can safely be closed
