### ISSUE TITLE
shell-pop breaks list-registers

### ISSUE THREAD

**Issue by wginolas** [kyagi/shell-pop-el#53]
Hi,

shell-pop uses a keyword symbol as register name (https://github.com/kyagi/shell-pop-el/blob/master/shell-pop.el#L308). This breaks list-register which tries to sort the registers by name.

    sort: Wrong type argument: number-or-marker-p, :shell-pop

The docstring of register-alist states that only characters are allowed as register names.

**Comment by syohex** [comment]
I have sent PR about replacing using register implementation at #54.

**Comment by wginolas** [comment]
That was fast! Thank you very much!

**Comment by syohex** [comment]
Merged #54.
