### ISSUE TITLE
 The layout was not expected when the shell was first opened.

### ISSUE THREAD

**Issue by guidao** [kyagi/shell-pop-el#59]
➜  elpa git:(master) ✗ emacs --version
GNU Emacs 26.1

System: mac osx

Reproduce:
1. emacs -Q
2. (require 'shell-pop)
3. (shell-pop nil)

ps: Appear only in full screen

![image](https://user-images.githubusercontent.com/3192136/49684853-85f2ce00-fb14-11e8-9a2a-4aedc1810236.png)

**Comment by Fuco1** [comment]
What did you expect to happen?  Did you look at the user options to configure this?
