### ISSUE TITLE
Full Width when split 2 window with 1 Treemacs 

### ISSUE THREAD

**Issue by DaoHuyTuan** [kyagi/shell-pop-el#63]
I have 1 Treemacs is opening and 2 window split vertical when i use shell-pop the shell allway full width but only avoid the  width of Treemacs 
[
<img width="2389" alt="Screen Shot 2019-06-05 at 1 14 43 AM" src="https://user-images.githubusercontent.com/26370399/58903357-7228cd00-872f-11e9-9de7-74af55b48591.png">
](url)
this what i want (i use demo from vscode)

<img width="2503" alt="Screen Shot 2019-06-05 at 1 23 48 AM" src="https://user-images.githubusercontent.com/26370399/58903874-9d5fec00-8730-11e9-895b-63ba47e44308.png">
this what i get i hope i can have some custom for this 

Your work is very great i hope you build more something great in the future :)
Thanks

**Comment by kyagi** [comment]
Would you try to turn `shell-pop-full-span` on?  
https://github.com/kyagi/shell-pop-el#shell-pop-full-span

**Comment by DaoHuyTuan** [comment]
yes i turn it on so every time it allway full width the second image is the result you can see

**Comment by DaoHuyTuan** [comment]
i just want it not hidden the treeemacs on the left side and allway full width of the other window like the first image i demo from vscode
