### ISSUE TITLE
How To see History output

### ISSUE THREAD

**Issue by LiuYinCarl** [kyagi/shell-pop-el#69]
I use shell-pop to run a gcc compile command, but compile failed and there are  a long output more than 30 lines, I want to see all the output after I run the gcc command. In the shell-pop window, I try `M-v`, `C-p`, `up`, `C-x [`, `Page Up`, but no command is available. then I try to read the shell-pop source code, but find nothing to help me solve the problem.  

I try both `'(shell-pop-term-shell "/bin/bash")` and `'(shell-pop-term-shell "/bin/fish")`, the result is same.

So, Is there a way to see the shell-pop's history output? Thanks for any suggestions.

**Comment by LiuYinCarl** [comment]
My .emacs config:

```elisp
(use-package shell-pop
  :init
  (setq shell-pop-default-directory "~"
        shell-pop-shell-type (quote ("ansi-term" "*ansi-term*" (lambda nil (ansi-term
shell-pop-term-shell))))
        shell-pop-term-shell "/bin/fish"
        shell-pop-universal-key "C-t"
        shell-pop-window-size 30
        shell-pop-full-span t
        shell-pop-window-position "bottom"
        shell-pop-autocd-to-working-dir t
        shell-pop-restore-window-configuration t
        shell-pop-cleanup-buffer-at-process-exit t)
  )
```

**Comment by syohex** [comment]
I suppose your issue is ansi-term mode issue. You can move buffer or copy output etc by switching line mode by `C-c C-j`. You need to back to char-mode by `C-c C-k` after buffer operations.

Reference
- https://www.gnu.org/software/emacs/manual/html_node/emacs/Term-Mode.html

**Comment by LiuYinCarl** [comment]
@syohex It works, thank you. I will close the issue..
